#!/bin/bash

DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
NAME=`basename "$0"`

export PIPENV_PIPFILE="${DIRECTORY}/Pipfile"
pipenv run python3 "${DIRECTORY}/${NAME}.py" "$@"
