#!/usr/bin/env python3

import argparse
import copy
import enum
import logging
import re
import subprocess


class Version(object):

    def __init__(self, major=0, minor=0, patch=0):
        self.major = major
        self.minor = minor
        self.patch = patch
        self.did_update_major = False
        self.did_update_minor = False
        self.did_update_patch = False

    def bump_major(self):
        if self.did_update_major:
            return
        self.major = self.major + 1
        self.minor = 0
        self.patch = 0
        self.did_update_major = True

    def bump_minor(self):
        if self.did_update_minor:
            return
        self.minor = self.minor + 1
        self.patch = 0
        self.did_update_minor = True

    def bump_patch(self):
        if self.did_update_patch:
            return
        self.patch = self.patch + 1
        self.did_update_patch = True

    def __str__(self):
        return f"{self.major}.{self.minor}.{self.patch}"


def run(command):
    result = subprocess.check_output(command, stderr=subprocess.PIPE)
    lines = result.decode("utf-8").strip().split("\n")
    return lines


def commits(ref):
    return run(["git", "log", "--pretty=format:%H", ref])


def get_tags(sha):
    try:
        return run(["git", "describe", "--tags", "--exact-match", sha])
    except subprocess.CalledProcessError:
        return []


def tags(ref):
    result = []
    for commit in commits(ref):
        result.append(get_tags(commit))
    return result


def parse_version(tag, namespace=None):
    prefix = ""
    if namespace is not None:
        prefix = namespace + "_"
    sv_parser = re.compile(r"^" + prefix + r"(\d+).(\d+).(\d+)$")
    match = sv_parser.match(tag)
    if match:
        return Version(major=int(match.group(1)),
                       minor=int(match.group(2)),
                       patch=int(match.group(3)))
    raise ValueError("Not a version")


def latest_version(ref):
    # Iterate over the tags in the current branch and stop at the first valid version.
    sv_parser = re.compile(r"^(\d+).(\d+).(\d+)$")
    for tag_list in tags(ref):
        found = False
        for tag in tag_list:
            match = sv_parser.match(tag)
            if match:
                return Version(major=int(match.group(1)),
                               minor=int(match.group(2)),
                               patch=int(match.group(3)))
    return Version()


class Commit(object):

    def __init__(self, sha, message, tags, version):
        self.sha = sha
        self.message = message
        self.tags = tags
        self.version = version


def version_from_tags(tags, namespace=None):
    for tag in tags:
        try:
            return parse_version(tag, namespace)
        except ValueError:
            pass
    return None



def get_commits(ref, namespace=None, stop=lambda x: False):
    results = []
    commits = run(["git", "log", "--pretty=format:%H:%s", ref])
    for c in commits:
        sha, message = c.split(":", 1)
        commit = Commit(sha, message, get_tags(sha), version_from_tags(get_tags(sha), namespace))
        results.append(commit)
        if stop(commit):
            return results
    return results


class Type(enum.Enum):
    FEATURE = "feat"
    FIX = "fix"
    BREAKING_CHANGE = "BREAKING CHANGE"
    UNKNOWN = "UNKNOWN"


OPERATIONS = {
    Type.BREAKING_CHANGE: lambda x: x.bump_major(),
    Type.FEATURE: lambda x: x.bump_minor(),
    Type.FIX: lambda x: x.bump_patch(),
    Type.UNKNOWN: lambda x: None,
}


class Message(object):

    def __init__(self, type, scope, description):
        self.type = type
        self.scope = scope
        self.description = description


def parse_message(message):
    cc_parser = re.compile(r"^(.+?)(\((.+?)\))?:(.+)$")
    match = cc_parser.match(message)
    if match is not None:
        (cc_type, cc_scope, cc_description) = (match.group(1), match.group(3), match.group(4))
        try:
            return Message(type=Type(cc_type),
                           scope=cc_scope,
                           description=cc_description.strip())
        except ValueError:
            pass
    return Message(type=Type.UNKNOWN,
                   scope=None,
                   description=message.strip())


def main():
    parser = argparse.ArgumentParser()
    # parser.add_argument("changelog", help="changelog to update")
    parser.add_argument("command", choices=["current-version", "current-changes", "tagged-version", "tag-release"])
    parser.add_argument("--namespace", help="namespace to be used in tags and commit messages")
    options = parser.parse_args()

    cc_parser = re.compile(r"^(.+?):.+")

    # Get all the commits up to and including the most recent commit tagged with a version.
    changes = get_commits("main", namespace=options.namespace, stop=lambda x: x.version is not None)
    changes.reverse()

    # Determine the starting version by checking to see if the first commit has a version tag.
    # If it does, update the version and discard the first tag as we assume any change it describes is already captured
    # in that version.
    initial_version = Version()
    first_commit = changes[0]
    if first_commit.version is not None:
        initial_version = first_commit.version
        changes = changes[1:]
    version = copy.deepcopy(initial_version)

    logging.debug(f"{version} (current release)")

    # Walk the commits to determine the next version.
    for commit in changes:
        message = parse_message(commit.message)
        if message.type in OPERATIONS:
            OPERATIONS[message.type](version)
        else:
            logging.warning("Ignoring unknown commit: '%s'", message.description)

    # Output the relevant information.
    if options.command == "current-version":
        print(version)
    elif options.command =="current-changes":
        for commit in changes:
            print(commit.message)
    elif options.command == "tagged-version":
        print(initial_version)
    elif options.command == "tag-release":
        # TODO: This should allow the --release-candidate flag and auto-increment release candidates.
        tag = str(version)
        if options.namespace is not None:
            tag = f"{options.namespace}_{tag}"
        run(["git", "tag", str(version)])


if __name__ == "__main__":
    main()